### ISSUE TITLE
Config file for library

### ISSUE THREAD

**Issue by bashfulrobot** [Girbons/comics-downloader#143]
**Is your feature request related to a problem? Please describe.**

- Remembering what titles I am downloading "feels" clunky. Having some way to manage a "library" might be good.

**Describe the solution you'd like**

- It would be super handy to define all the comics you want to watch and download by specifying a list in a config file (i.e. yaml). Then, there is no need to remember all the items you are downloading.  You could then pass in the config with the daemon option to auto-download.

**Describe alternatives you've considered**

- My current solution is maintaining a shell script that calls your binary.

**Comment by Girbons** [comment]
> It would be super handy to define all the comics you want to watch and download by specifying a list in a config file (i.e. yaml). Then, there is no need to remember all the items you are downloading. You could then pass in the config with the daemon option to auto-download.

this is just for daemon mode right?

**Comment by bashfulrobot** [comment]
Could be for a cli invocation as well. For example, I move my stuff to a
reader, so I have no need for the binary to be constantly running. Just
when I plan to update what’s available.

Cheers,
— Dustin

**Comment by bashfulrobot** [comment]
Yes, I also wrote wrapper scripts as well. 👍

**Comment by bashfulrobot** [comment]
Using something like YAML or TOML would work. 

As an example (fictional):

```
# Comics Downloader Configuration File

# Comics watchlist
comics:
  - name: "One Piece"
    url: "https://mangakakalot.com/manga/one-piece"
    scope: "last"                     # Options: last, all, range (e.g., "1-10")
    output: "comics/manga/one-piece"
    images_format: "jpg"              # Options: jpg, png, jpeg, img
    format: "cbz"                     # Options: pdf, epub, cbr, cbz
    custom_comic_name: ""
    force_aspect: false
    
  - name: "Batman"
    url: "https://readcomiconline.li/Comic/Batman"
    scope: "range:50-60"
    output: "comics/dc/batman"
    images_format: "png"
    format: "pdf"
    custom_comic_name: "Batman - Rebirth"
    force_aspect: true
    
  - name: "Attack on Titan"
    url: "https://www.mangareader.tv/manga/attack-on-titan"
    scope: "all"
    output: "comics/manga/aot"
    images_format: "jpg"
    format: "cbz"
    custom_comic_name: "Attack on Titan"
    force_aspect: false
    
  - name: "Spider-Man"
    url: "https://comicextra.net/comic/amazing-spider-man"
    scope: "last"
    output: "comics/marvel/spider-man"
    images_format: "jpg"
    format: "cbr"
    custom_comic_name: "Amazing Spider-Man"
    force_aspect: false
    
  - name: "Naruto"
    url: "https://manganato.com/manga/naruto"
    scope: "range:700-720"
    output: "comics/manga/naruto"
    images_format: "jpeg"
    format: "pdf"
    custom_comic_name: "Naruto - Final Arc"
    force_aspect: true
    
  - name: "My Hero Academia"
    url: "https://www.mangatown.com/manga/boku_no_hero_academia"
    scope: "last"
    output: "comics/manga/mha"
    images_format: "jpg"
    format: "epub"
    custom_comic_name: "My Hero Academia"
    force_aspect: false
```

Then, if you run the tool with the config in an expected location (ie `~/.config/comics-dowloader/watchlist.yaml`), or if added as a flag (ie `comics-downloader -watch-list watchlist.yaml`) it will just run through the list and perform the actions.
